// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htxdqswbajzhdzhawfih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0eGRxc3diYWp6aGR6aGF3ZmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzU4NDYsImV4cCI6MjA2MTg1MTg0Nn0.xwisG6hXHXoDbb_l2LTxbH3ZhZb6SPG3VclAze7nO7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);